name: Build OnlyOffice Linux ARM64 server
on:
  push:
    branches:
      - release/v8.1.0
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Docker Setup Docker
      uses: docker/setup-docker-action@v4.6.0
    - name: Build project
      id: build_step
      run: |
        git clone --branch ${{ github.ref_name }} https://github.com/hxp-plus/build_tools.git
        mkdir out
        docker build --build-arg PLATFORM=linux_arm64 --build-arg BRANCH=v8.1.0.178 --build-arg HTTP_PROXY=${HTTP_PROXY} --build-arg HTTPS_PROXY=${HTTPS_PROXY} --tag onlyoffice-document-editors-builder:v8.1.0 .
        docker run --name onlyoffice-builder -v $PWD/out:/build_tools/out onlyoffice-document-editors-builder:v8.1.0
    - name: Package tar.gz
      run: |
        VERSION=$(echo ${{ github.ref_name }} | sed 's/^release\/v//')
        mv out OnlyOffice-Linux-ARM64
        tar zcvf OnlyOffice-Linux-ARM64.$VERSION.tar.gz OnlyOffice-Linux-ARM64
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-files
        path: OnlyOffice-Linux-ARM64
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: compiled-files
        path: ./output
    - name: Create Release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 使用 shell 移除 'v' 前缀
        CLEAN_VERSION=$(echo ${{ github.ref_name }} | sed 's/^release\/v//')
        echo "Creating release with version: $CLEAN_VERSION"
        gh release create $CLEAN_VERSION -t "Release $CLEAN_VERSION" -n "" --repo ${GITHUB_REPOSITORY}
        echo "::set-output name=upload_url::$(gh release view $CLEAN_VERSION --json url | jq -r '.url')/assets"
    - name: Set version environment
      run: echo "CLEAN_VERSION=$(echo ${{ github.ref_name }} | sed 's/^release\/v//')" >> $GITHUB_ENV
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/
        asset_name: OnlyOffice-Linux-ARM64.${{ env.CLEAN_VERSION }}.tar.gz
        asset_content_type: application/octet-stream
